### ISSUE TITLE
[mobile] UI improvements - excluding Map

### ISSUE THREAD

**Issue by TDSOJohn** [SeC-Hikit/Hikit-Frontend-CAIBO#47]
The mobile UI has some problems. Most of them are highlighted here:

https://drive.google.com/file/d/16rxRzuACF7bnPaTcFD_BUESs5bQhaAeb/view?usp=share_link

**Comment by loreV** [comment]
- Segnalazioni di percorrenza:
  -- Nascondere immaginina in mobile
  -- Modal centrata 
- Aggiustare tabella calendario manutenzioni:
  -- nascondere campo contatto quando mobile
  -- nascondere time dal datetime
  -- ellipsis quando il testo è troppo lungo (Nice to have)
- Allineare le tabelle 100% width
